# -*- coding: utf-8 -*-
"""streamlit_deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCpbY06AyvZl10Lla0NB_Mpm53l3Yr1b
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open('rfModel.pkl', 'rb') as file:
    model = pickle.load(file)

# Create a function to make predictions
def predict_heart_disease(inputs):
    prediction = model.predict([inputs])
    return prediction[0]

# Streamlit app
st.title("Heart Disease Prediction")

# Input features
age = st.number_input("Age", min_value=0, max_value=120, value=50)
sex = st.selectbox("Sex", options=[0, 1], format_func=lambda x: "Male" if x == 1 else "Female")
cp = st.selectbox("Chest Pain Type (cp)", options=[0, 1, 2, 3])
trestbps = st.number_input("Resting Blood Pressure (trestbps)", min_value=0, max_value=300, value=120)
chol = st.number_input("Serum Cholestoral (chol)", min_value=0, max_value=600, value=200)
fbs = st.selectbox("Fasting Blood Sugar > 120 mg/dl (fbs)", options=[0, 1])
restecg = st.selectbox("Resting Electrocardiographic Results (restecg)", options=[0, 1, 2])
thalach = st.number_input("Maximum Heart Rate Achieved (thalach)", min_value=0, max_value=300, value=150)
exang = st.selectbox("Exercise Induced Angina (exang)", options=[0, 1])
oldpeak = st.number_input("ST Depression Induced by Exercise (oldpeak)", min_value=0.0, max_value=10.0, value=1.0, format="%.1f")
slope = st.selectbox("Slope of the Peak Exercise ST Segment (slope)", options=[0, 1, 2])
ca = st.selectbox("Number of Major Vessels (ca)", options=[0, 1, 2, 3])
thal = st.selectbox("Thalassemia (thal)", options=[0, 1, 2, 3])

# Make prediction
inputs = np.array([age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal])
if st.button("Predict"):
    result = predict_heart_disease(inputs)
    st.write(f"The model predicts: {'Presence of heart disease' if result == 1 else 'Absence of heart disease'}")